version: '3.9'

services:
  frontend-dev:
    container_name: frontend-dev
    image: frontend-dev:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    env_file:
      - .env.local
  frontend-prod:
    container_name: frontend-prod
    image: frontend-prod:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
    env_file:
      - .env
